apiVersion: apps/v1
kind: Deployment
metadata:
  name: starlight-plugins-docs-components
  namespace: starlight-plugins-docs-components
  labels:
    app: starlight-plugins-docs-components
spec:
  replicas: 3
  selector:
    matchLabels:
      app: starlight-plugins-docs-components
  template:
    metadata:
      labels:
        app: starlight-plugins-docs-components
    spec:
      containers:
        - name: starlight-plugins-docs-components
          image: "trueberryless/starlight-plugins-docs-components:main-71e09cee2f6df3fb9eb80855b4beb9057dfefe6f"
          imagePullPolicy: Always
